### ISSUE TITLE
[YouTube for Trailers] Error, unable to find content (yt-dlp)

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#1005]
Looks like yt-dlp is failing to do the nsig signatures again.
Cant see any updates on master yet.

need to investigate if we can use the other formats it returns instead in these situations to make more robust!

**Comment by matthuisman** [comment]
fixed now in new version of SlyGuy trailers [slyguy.trailers -> v0.0.2](https://github.com/matthuisman/slyguy.addons/commit/4ef760961add6545e2a28cfa35fb94961d855dc9)

**Comment by johnnygal** [comment]
I just stumbled on your plugin yesterday in (another) battle trying to get trailers working again, so thanks for this. I installed but got the error you just fixed here. But it still doesn't work for me. 
I get the error:

"SlyGuy Trailers Error"
Can not playback using SlyGuy redirect addon
plugin.video.youtube


(When I updated the add-on for this fix, it seemed to jump from the video add-on section to the services section if this is related?)

**Comment by matthuisman** [comment]
im working a blog post now about it.

Basically this has happened

"There will be a new plugin called "SlyGuy Trailers".
The trailer stuff will be shifted to that from slyguy common.
The "Youtube for trailers" will be renamed to "YouTube -> SlyGuy Trailers" as all it does it redirect the plugin://youtube trailer paths that Kodi scrapes into my new plugin.

There is also a "Tubed -> SlyGuy Trailers" which does the same thing for any scraped plugin://tubed trailers.
This is the only way we can get the "Information -> Trailers" to use my code.

For the Content menu - that always comes straight into my code so no redirects needed.
Once they get into my plugin - it can do the yt-dlp or Youtube APK behaviour etc"

So, all settings are now found in SlyGuy trailers addon.
The "Youtube" / "Tubed" have no settings as they are literally a few lines of code to redirect to this new plugin.

**Comment by johnnygal** [comment]
Thanks for the explanation. I found the slyguy trailers I had was only at version v0.0.3 and there's been a few updates in the last day or so, I didn't see it as it is no loinger in the video addons section in the UI. Once I updated to v0.0.6 it's all working ok.

Many thanks for your work on this add-on, reallyuseful having trailers again.

**Comment by matthuisman** [comment]
blog post is now up:
https://www.matthuisman.nz/2025/04/slyguy-trailers-kodi-add-on.html

its not yet complete but should hopefully explain a bit more :)

**Comment by matthuisman** [comment]
Blog post above is now complete :)
