### ISSUE TITLE
Subtitles disappearing

### ISSUE THREAD

**Issue by zw4mp** [matthuisman/slyguy.addons#1107]
While watching for example Friends, subtitles disappear after half of the show.

It works when watching in a browser, but then there is an ad-break in the middle of the show.

**Comment by matthuisman** [comment]
Which addon?

**Comment by zw4mp** [comment]
Sorry realised it needed some tag. HBO Max

**Comment by matthuisman** [comment]
What version Kodi / inputstream.adptive versions?
Pretty sure this might already be fixed

**Comment by zw4mp** [comment]
Kodi: 21.2.0
Inputstream: 21.5.16
Hbo Max: 0.2.6

**Comment by zw4mp** [comment]
My subscription is "Basic with ads" through swedish Telia

**Comment by matthuisman** [comment]
90% sure it was an inputstream.adaptive issue that is fixed in Kodi 22

I'll try to find some info

**Comment by zw4mp** [comment]
Ok then I'll have to wait for that :)

External subtitles are working for now so no worries.

**Comment by matthuisman** [comment]
Ive had reports this is indeed fixed in Kodi 22 version of inputstream.adaptive

**Comment by nonobio** [comment]
Hi,
I have the same problem. The subtitles work for the first 10 minutes or so, then disappear.
Do I absolutely need Kodi version 22, or was it fixed in version 21.3? I'm sharing MySQL and it's a bit of work to upgrade to 22, and I often avoid it while it's in beta.
I am currently in LibreElec Kodi version 21.2, and I have a problem updating to 21.3.
Thanks

**Comment by nonobio** [comment]
I tested on another device running Kodi 21.3 (Windows), and the issue is still present. It seems that Kodi 22 is indeed required to fix it.

However, I was able to switch back to watching HBO Max content via the Amazon add-on (an audio stream issue has now been resolved), and in this case, the subtitle problem does not occur.
