### ISSUE TITLE
script.module.inputstreamhelper

### ISSUE THREAD

**Issue by Publish3r** [matthuisman/slyguy.addons#478]
Hi Matt.
Your version of the script.module.inputstreamhelper is not working with addons from other coders.
Since today (v99.0.1) i always get the error "No module named 'slyguy'".
Maybe it's better to rename your inputstreamhelper, so it's possible to run both versions without any conflicts?

**Comment by matthuisman** [comment]
Kodi should not be installing mine by default if there is one in its own
repo......
It should have had to be manually installed.

**Comment by matthuisman** [comment]
id needs to be the same. the whole point is it replaces the other version :)

Jus pushed an update that should fix that errror

**Comment by mmanuxx** [comment]
v99.0.2 didn't fix it for me. Kodi recognizes it as an update from v0.6.1+. Once updated to yours, Amazon prime video plugin playback failed. Reinstalling v0.6.1+ fixed it and your video plugins and Amazon prime video work again. I initially didn't know why prime video stopped working. Some users of both may start bug reporting there unaware.

**Comment by matthuisman** [comment]
do you have "update official addons from" set to "any repositories" in the kodi settings?

**Comment by matthuisman** [comment]
ive removed it from my repo for now. didnt think kodi would update to a 3rd party repo automatically. i wanted it to be for users who wanted it

**Comment by Shreyas-Alse** [comment]
How can I install it?

**Comment by Shreyas-Alse** [comment]
It will update if set so in settings (only official addons is the default setting)

**Comment by mmanuxx** [comment]
> do you have "update official addons from" set to "any repositories" in the kodi settings?

Yes but also set to notify but don't install. So I see before updating, however I've never had an issue updating any of your addons so whenever I see slyguy updates there's no hesitation. It's only after remembering this update that I realized this may be the culprit as to why prime video stopped working.

**Comment by matthuisman** [comment]
would you have the error that prime video raised?
Looking at its code, i cant see why it wouldnt work

**Comment by matthuisman** [comment]
@Shreyas-Alse 
https://f.mjh.nz/.temp/script.module.inputstreamhelper.zip

**Comment by mmanuxx** [comment]
> @mmanuxx would you have the error that prime video raised? Looking at its code, i cant see why it wouldnt work

Found this. Not sure if its applicable. Copied from the log save for the movie title.

`2023-06-15 22:32:41.827 T:5148    error <general>: `anonymous-namespace'::GetItemsForPlayList: Unable to get playlist items for plugin://plugin.video.amazon-test/?asin=B0876D5PKF&mode=PlayVideo&name=MOVIENAME&adult=0&trailer=0&selbitrate=0
2023-06-15 22:32:42.387 T:12008 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-06-15 22:32:48.438 T:3212     info <general>: Skipped 58 duplicate messages..
2023-06-15 22:32:48.438 T:3212    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 69, in EntryPoint
                                                       from .playback import PlayVideo
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 11, in <module>
                                                       from inputstreamhelper import Helper
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\resources\modules\inputstreamhelper\__init__.py", line 1, in <module>
                                                       from slyguy import inputstream
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\__init__.py", line 3, in <module>
                                                       from .log import log
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\log.py", line 5, in <module>
                                                       from .constants import LOG_ID, LOG_FORMAT
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\modules\slyguy\constants.py", line 10, in <module>
                                                       ADDON_PATH     = xbmc.translatePath(ADDON.getAddonInfo('path'))
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   `

**Comment by matthuisman** [comment]
Perfect. 99% sure it's a sys.path issue

**Comment by matthuisman** [comment]
Was there another log message somewhere about the sys.path?

**Comment by Shreyas-Alse** [comment]
I will send u the full log..

**Comment by Shreyas-Alse** [comment]
https://paste.kodi.tv/uporufapeb.kodi

**Comment by matthuisman** [comment]
that log was using 99.0.1 not 99.0.2
99.0.2 has a different error. i think i can figure it out without log

**Comment by mmanuxx** [comment]
attached is the full log

 
 

Sent: Friday, June 16, 2023 at 1:50 AM

**Comment by matthuisman** [comment]
ok. try latest slyguy common and inputsream helper that have just been pushed

**Comment by mmanuxx** [comment]
no luck. had to revert again. log attached.

 
 

Sent: Friday, June 16, 2023 at 4:08 AM

**Comment by matthuisman** [comment]
this is 2nd time no log is actually attached?
I dont think attachments on emails show.

Please open in browser and add log

**Comment by theoden11** [comment]
I can confirm all the problem described. I had to manually reinstall the default inputstream.helper from the default Kodi matrix repository, and your inputstream addon is always marked as an update. When my system updated yesterday, nothing worked after that : nor Amazon, nor Live TV, nor Netflix, same error and log "No module named 'slyguy'". Everything of course is up to date, and the problem occurs on all platforms (Anrdoid TV, Windows 11, libreelec and osmc).

**Comment by matthuisman** [comment]
@theoden11 set "update official addons from" to "official repository"

**Comment by Shreyas-Alse** [comment]
Thanks a lot.. I will try once I get home 😊

**Comment by Shreyas-Alse** [comment]
It worked 😊 thanks a lot for all your help and cooperation 😀

**Comment by matthuisman** [comment]
yah :) got there in the end!

**Comment by nebulous42069** [comment]
Heres one error from Daddylive addon. Doesnt throw an error, but fails to play the stream. 
2023-06-18 21:53:15.806 T:25636 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-06-18 21:53:16.212 T:5824    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.daddylive/?mode=play&url=https%3A%2F%2Fdaddylivehd.sx%2F%2Fstream%2Fstream-31.php]
2023-06-18 21:53:23.208 T:25052 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-06-18 21:53:23.634 T:5824    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.daddylive/?mode=play&url=https%3A%2F%2Fdaddylivehd.sx%2F%2Fstream%2Fstream-39.php]

**Comment by nebulous42069** [comment]
The recent 99.05 did fix a few of the addons that werent working before, but this one still wont work with it. Ill test some more addons to see if I can find another or not.

**Comment by nebulous42069** [comment]
[plugin.video.daddylive.zip](https://github.com/matthuisman/slyguy.addons/files/11783378/plugin.video.daddylive.zip)

If you want to test, this one doesnt work with 99.05, but works with official.

**Comment by matthuisman** [comment]
can you check your log and see if its attempting to use inputstream.adaptive or simply using ffmpeg?

**Comment by Shreyas-Alse** [comment]
I had to check the 'Disable inputstream check' in the inputstream wrapper settings to make amazon prime work. So do try that..

**Comment by matthuisman** [comment]
oh. thats not a solution :( that literally just skips most of it

**Comment by matthuisman** [comment]
is daddylive an addon i can run without login etc?

**Comment by Shreyas-Alse** [comment]
Yes it doesn't need login.

**Comment by matthuisman** [comment]
thanks everyone.

Latest slyguy common [v0.66.9](https://github.com/matthuisman/slyguy.addons/commit/050f3f4f5162847253f7bb637483ab130d8587c4) should fix the issues!

Please test with the IA helper "skip check" disabled across all addons!

**Comment by nebulous42069** [comment]
Nice job finding the fix. Seems to be all good here. Thanks!

**Comment by matthuisman** [comment]
thanks for being patient!

**Comment by nebulous42069** [comment]
Just curious if you dont mind, what are the benefits to your IS helper version?

**Comment by matthuisman** [comment]
was simply added for @Shreyas-Alse who was having issues with the standard IA helper as per:
https://github.com/matthuisman/slyguy.addons/issues/477

If your using ARM - mine is quicker as it doesnt download a large chromium image

**Comment by nebulous42069** [comment]
Gotcha, thanks!
