### ISSUE TITLE
Paramount+ UEFA Champions League section

### ISSUE THREAD

**Issue by ashtoncain** [matthuisman/slyguy.addons#535]
Hi,

Firstly, thank you for making these amazing addons which i love !!

I am unable to access the UEFA Champions League section. I get an error code which is "KeyERROR: 'VideoSectionMetadata'

Is this something that could be fixed?

Thanks

**Comment by matthuisman** [comment]
what country are you in please?

**Comment by ashtoncain** [comment]
Hi,

I am in the UK but using VPN for USA. Can confirm the Champions League section works on the official android app

**Comment by ashtoncain** [comment]
Hi Matt, is there any update on this?

Thanks

**Comment by matthuisman** [comment]
Not yet. Can you search for the games in the meantime?

**Comment by ashtoncain** [comment]
I did try that yesterday but if search for a team, it then asks me to click into the category. Then i get the same error. Do you have the same issue for that section?

**Comment by matthuisman** [comment]
I haven't had time to check yet

**Comment by ashtoncain** [comment]
Hi Matt,

Any update on whether this will be fixed? I can watch through the official app but i find when i can choose the quality in kodi, i get a better picture

**Comment by matthuisman** [comment]
ill try take a look at this issue tonight

**Comment by matthuisman** [comment]
fixed with [v0.6.8](https://github.com/matthuisman/slyguy.addons/commit/983150f388c0695380564c2af9dc236db4a0a0af)

**Comment by ashtoncain** [comment]
Awesome !! Will test when i get a chance. Thank you for fixing

**Comment by ashtoncain** [comment]
I have updated to 0.6.9 but still receiving an error message. It says expat error. I think others might be having the same issues also.

**Comment by matthuisman** [comment]
thats a separate issue.
see https://github.com/matthuisman/slyguy.addons/issues/542 (its fixed in 0.7.0)
