### ISSUE TITLE
Paramount+: Paramount+ is not available in your Region

### ISSUE THREAD

**Issue by xMisterW** [matthuisman/slyguy.addons#846]
KODI 22.0 ALPHA 1
Parmount Plus Addon 0.9.1

**Comment by marcmv1** [comment]
I can confirm this as well

**Comment by matthuisman** [comment]
looks like they have changed something. will have a look when time permits

**Comment by mj-saleh** [comment]
I can confirm that it happened to me in Australia (Parmount Plus Addon 0.9.1).
Paramount App works fine though.

**Comment by matthuisman** [comment]
it may be a whole new API from quick look.... confirming now.
If thats the case - it may be down for sometime as an entire rewrite of an addon is a major

**Comment by matthuisman** [comment]
false alarm.
they had just blocked the user-agent

fixed with [slyguy.paramount.plus -> v0.9.2](https://github.com/matthuisman/slyguy.addons/commit/3b8be54d2d03e9f4adecc86b3bb219a903bdf715)

**Comment by scottydulton** [comment]
now when logging in the not available in your location error is fixed but now its throwing the 'Failed to feth JSON data' geo location error

**Comment by mj-saleh** [comment]
Thanks for looking into this issue @matthuisman.
I still see V0.9.1 in the repo.

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by drsaxoncrawfish** [comment]
I am actually having this same issue, suddenly, on the newest version of the addon. Funny thing is I have two Raspberry Pi Kodi boxes, and Paramount+ works just fine on one of them, but the other one gives me this error. Neither of them are connected to a VPN, either.
