### ISSUE TITLE
ESPN plugin: streams buffer when returning from commercial and then play the same 30 second loop repeatedly.

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#872]
Please let me know what useful information can be proveded to troubleshoot.

**Comment by lionsnob** [comment]
Linux flatpak 21.1, X86 PC Xubuntu 22.04.

**Comment by matthuisman** [comment]
maybe fixed with latest slyguy commons pushed tonight.
please update to [script.module.slyguy -> v0.85.16](https://github.com/matthuisman/slyguy.addons/commit/bc0e7533e552ccc79c8976ce30abf5d9827b362b) and try again and let me know

**Comment by lionsnob** [comment]
Hello -

It's still happening, and I've attached a log.
[kodi.log](https://github.com/user-attachments/files/16767882/kodi.log)

**Comment by matthuisman** [comment]
could you test with quality set to BYPASS?

**Comment by matthuisman** [comment]
please try with latest [script.module.slyguy -> v0.85.18](https://github.com/matthuisman/slyguy.addons/commit/b20b4b49726d41ea65cdeafb54928099111c2d1d) and debug log again if that still fails :)

**Comment by lionsnob** [comment]
Hello - it's still happening unfortunately.
[kodi.tar.gz](https://github.com/user-attachments/files/16787662/kodi.tar.gz)

**Comment by matthuisman** [comment]
that log says your still on 0.85.16 (at the top)
Please update to .18 and then restart kodi for a fresh log and get that to me.

**Comment by lionsnob** [comment]
Hello - it still freezes sadly. Log attached.
[kodi.log](https://github.com/user-attachments/files/16790576/kodi.log)

**Comment by matthuisman** [comment]
no more errors / execptions / 404's - thats good. That is what I was trying to fix last few nights.
so the issue now could either by the proxy or inputstream.adaptive not liking whatever this stream is doing

Lets try no proxy (with new debug log please)
ESPN -> Settings -> Player -> Advanced -> SlyGuy Proxy -> set to No
Then let it play and see if same issue :)

**Comment by lionsnob** [comment]
Still no luck! Log attached. I did disable the proxy.
[kodi.log](https://github.com/user-attachments/files/16802570/kodi.log)

**Comment by matthuisman** [comment]
thanks :) So yup, think its an inputstream adaptive issue.
We will need to provide them with the manifest file etc.
They usually save them in the inputstream.adaptive userdata dir / manifests

**Comment by usphil** [comment]
On Kodi 19 device, common module 0.84.42 ESPN v0.3.5, inputstream.adaptive 19.0.7.1, channels ESPN, ESPN 2, ESPN U, ESPN News run without any errors. 
Meanwhile, on Kodi 20 Nexus device, common module 0.85.19, ESPN v0.4.0, inputstream.adaptive version 20.3.18.1, channels ESPN, ESPN 2, ESPN U, ESPN News keep repeating after 15 seconds. 
ESPN+ channels have no problems

**Comment by matthuisman** [comment]
On the 19 update the addon's to latest. If still ok, then we can be pretty
confident it's inputstream adaptive
